### ISSUE TITLE
MyGames: Filtrering av spill basert på sjanger

### ISSUE THREAD

**Issue by tilen1976** [Gruppe5UIN/Eksamen_Gruppe5#70]
I DashBoard seksjon MyGames:
Legge til filtrering på sjanger 
Vise 4 (?) spill fra denne sjanger i DashBoard
Vise alle spill fra sjanger i MyGames
Kunne endre sjanger  i MyGames

**Comment by slosne** [comment]
Closer denne, fordi jeg har lagt en ny issue og ny branch.
